baseURL = "http://www.yazen.xyz"
title = "YAZEN"
description = "YAZEN"
DefaultContentLanguage = "en"
copyright = "YAZEN"

[params]
  ga_analytics='UA-142977531-1'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products"
    weight = 2
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
    weight = 3

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  
  [languages.ja]
    languageName = "Japanese"
    weight = 2
    [[languages.ja.menu.main]]
    url    = "/"
    name   = "Home"
    weight = 1
    [[languages.ja.menu.main]]
    url    = "/ja/products"
    name   = "Products"
    weight = 2
    [[languages.ja.menu.main]]
    url    = "/ja/blog"
    name   = "Blog"
    weight = 3